import { Geist, Geist_Mono } from "next/font/google";
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import '../../node_modules/@fortawesome/fontawesome-free/css/all.min.css'
import "./globals.css";
import Navbar from "./_mainlayout/_navbar/navbar";
import Footer from "./_mainlayout/_footer/page";
import BootstrapClient from "./_mainlayout/bootstrap/BootstrapClient.js";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  
  return <>
    <html lang="en">
      <body >
        <Navbar></Navbar>
        {children}
        <BootstrapClient></BootstrapClient>
        <Footer></Footer>
      </body>
    </html>
  </>

}


//className={`${geistSans.variable} ${geistMono.variable}`}